services:
  # websocket gateway
  ws-gateway:
    build: ./src/gateway
    ports:
      - "8080"
    environment:
      - WS_PORT=1234
      - MONGODB_URI=mongodb://mongo:27017/collab_notes
      - JWT_SECRET=my_super_secret_123
    networks:
      - app-network

  # Nginx reverse proxy, load balancer
  nginx:
    build: ./src/nginx # Chúng ta sẽ viết Dockerfile riêng cho Nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - APP_SERVICE_NAME=collab_notes-ws-gateway
      - APP_PORT=1234
    depends_on:
      - ws-gateway
    restart: unless-stopped
    networks:
      - app-network

  # Dịch vụ MongoDB
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

    # THÊM SERVICE REDIS
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local

networks:
  app-network:
    driver: bridge
